version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-tier

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "test-kafka-1:1:1"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - app-tier

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-tier
    volumes:
      - ./:/var/www/html

  php-worker:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-tier
    volumes:
      - ./:/var/www/html
    command: php index.php worker:process-notification
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-tier

